title: Your awesome title
author:
  name: Antide Duraffour
  email: your-email@domain.com

description: >
  Write an awesome description for your new site here. You can edit this line
  in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false
