title: Antide Duraffour Mathematical Website
author:
  name: Antide Duraffour
  email: antide.duraf[arobase]gmail.com

description: >
  I am a postdoctoral researcher in Universit√© Grenobles Alpes working in semiclassical analysis.

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: classic

  nav_pages:
    - publications.md
    
  show_excerpts: false
